apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drone.fullname" . }}
  labels:
    app: {{ template "drone.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.drone.secret }}
  secret:  {{ .Values.drone.secret | b64enc | quote }}
  {{ else }}
  secret: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  git-client: {{ .Values.server.gitClient | b64enc | quote }}
  git-secret: {{ .Values.server.gitSecret | b64enc | quote }}
