apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: {{ .Values.server.name }}
  selector:
    app: {{ template "server.fullname" . }}
